/*
 * Offering.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This file was generated from tbdex-protocol/json-schemas. Run gradle generate
 */
package tbdex.model

data class Offering(
    /** Brief description of what is being offered. */
    val description: String,
    /** Number of quote currency units for one base currency unit (i.e 290000 USD for 1 BTC) */
    val quoteUnitsPerBaseUnit: String,
    val baseCurrency: BaseCurrency,
    val quoteCurrency: BaseCurrency,
    val payinMethods: List<PayinMethod>,
    val payoutMethods: List<PayinMethod>,
    /** PresentationDefinition that describes the credential(s) the PFI requires in order to provide a quote. */
    val requiredClaims: RequiredClaims
) {

    data class BaseCurrency(
        /** ISO 3166 currency code string */
        val currencyCode: String,
        /** Minimum amount of currency that can be requested */
        val minSubunits: String? = null,
        /** Maximum amount of currency that can be requested */
        val maxSubunits: String? = null
    )

    data class PayinMethod(
        /** The type of payment method. e.g. BITCOIN_ADDRESS, DEBIT_CARD, etc. */
        val kind: String,
        /** A JSON Schema containing the fields that need to be collected in order to use this payment method */
        val requiredPaymentDetails: RequiredPaymentDetails
    )

    /**
     * A JSON Schema containing the fields that need to be collected in order to use this payment method
     */
    open class RequiredPaymentDetails

    /**
     * PresentationDefinition that describes the credential(s) the PFI requires in order to provide a quote.
     */
    open class RequiredClaims

}
