/*
 * OrderStatus.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This file was generated from tbdex-protocol/json-schemas. You can regenerate by running `./gradlew generate`
 */
package tbdex.model

data class OrderStatus(
    val orderStatus: OrderStatus
) {

    enum class OrderStatus {
        PENDING,
        COMPLETED,
        FAILED
    }

}
