/*
 * Rfq.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 *
 * This file was generated from tbdex-protocol/json-schemas. Run gradle generate
 */
package tbdex.model

data class Rfq(
    /** Offering which Alice would like to get a quote for */
    val offeringId: String,
    /** Amount of quote currency you want to spend in order to receive base currency */
    val quoteAmountSubunits: String,
    /** Presentation Submission that fulfills the requirements included in the respective Offering */
    val claims: List<String>,
    val payinMethod: PayinMethod,
    val payoutMethod: PayinMethod
) {

    data class PayinMethod(
        /** Type of payment method e.g. BTC_ADDRESS, DEBIT_CARD, MOMO_MPESA */
        val kind: String,
        /** An object containing the properties defined in the respective Offering's requiredPaymentDetails json schema */
        val paymentDetails: PaymentDetails
    )

    /**
     * An object containing the properties defined in the respective Offering's requiredPaymentDetails json schema
     */
    open class PaymentDetails

}
